// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoAyZkth0p3K_Lipz8uJCr5fn3oBFWNZ0',
    appId: '1:969519467414:android:145bb03b1e505447ea6bb7',
    messagingSenderId: '969519467414',
    projectId: 'fir-test-9e966',
    storageBucket: 'fir-test-9e966.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDliCIZ9Zl4LDHGAAhT3Co1DlQC2Cy85b8',
    appId: '1:969519467414:ios:6c70c8f1cb87bc48ea6bb7',
    messagingSenderId: '969519467414',
    projectId: 'fir-test-9e966',
    storageBucket: 'fir-test-9e966.firebasestorage.app',
    iosBundleId: 'com.example.weatherProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4Ui42DeHT9TuOLeG5td_BQSgTawL2JA',
    appId: '1:969519467414:web:28b41ba4285f726cea6bb7',
    messagingSenderId: '969519467414',
    projectId: 'fir-test-9e966',
    authDomain: 'fir-test-9e966.firebaseapp.com',
    storageBucket: 'fir-test-9e966.firebasestorage.app',
    measurementId: 'G-3KSLNXHQKN',
  );
}
